import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
import './refinements.css';

const FAB='https://www.fab.com/listings/d5ce0b45-8c80-486d-8316-882856198875';
const DOCS='https://docs.google.com/document/d/1TI85713-m77ffLTBt8gXm0qnTO-rZNs4cMDOiOCsAPc/edit?usp=sharing';
const DISCORD='https://discord.gg/PnuU3eW8J';
const scenes=[['176ba55a','Soul Cave','Hassnain Aly'],['3b3de8bc','Evermotion Archinterior Scene','Walhar Gohar'],['663fbcd3','Art Gallery Interior','Alejandro Nevárez'],['692c4f91','UE5 City Sample – Small Part','Walhar Gohar'],['71111000','T4 Apartment','Andy Praseetyo'],['797f5c99','Apollo Moon Lander – Lumen Reflections','Walhar Gohar'],['c37cb759','Studio 11','Goce Milanoski'],['3c0f3775','Derelict Corridor','Walhar Gohar'],['b7c8d8c5','Interior Space','NBV.Studio'],['9ae3b553','Epic Games Hillside Sample','Walhar Gohar']];
const modes=[
 ['product','Product Capture','Object-focused layouts with bounds-aware aiming.','/product-capture.webp'],
 ['path','Path Capture','Editable spline routes with overlapping cameras.','/path-capture.webp'],
 ['volume','Volume Capture','Room and space coverage with clearance filtering.','/volume-capture.webp'],
 ['aerial','Oblique Aerial Capture','Configurable aerial routes for large exterior maps.','/oblique-aerial-capture-v2.webp']
];
const faqs=[['Does Unreal to Gaussian Splat train the final Gaussian Splat?','No. The plugin generates the COLMAP-ready dataset used for training. Training happens afterward in compatible software such as Postshot or LichtFeld Studio.'],['Does the plugin render Gaussian Splats inside Unreal Engine?','No. It is an editor-only dataset-generation tool.'],['Do I need to manually align cameras in COLMAP?','No manual camera alignment or external COLMAP reconstruction is required.'],['Can I change point-cloud density after capturing images?','Yes. Version 3.0 allows point-cloud density to be selected after image capture.'],['Which Unreal Engine versions are supported?','Windows with Unreal Engine 5.4, 5.5, 5.6, 5.7 and 5.8.'],['What can I use to train the exported dataset?','Postshot, LichtFeld Studio and other COLMAP-compatible Gaussian Splatting / NeRF trainers.']];
const iteration=['Add additional cameras','Preview captured views','Preview pending views','Inspect RGB images','Change density after capture','Generate independently','Color independently','Export independently','Optional .ply','Object masks'];
const Arrow=()=> <span aria-hidden="true">→</span>;

function PointCloud(){
 const canvas=useRef(null),mouse=useRef({x:-1000,y:-1000,active:false}),frame=useRef();
 useEffect(()=>{const c=canvas.current,ctx=c.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let w,h,pts=[];
  const resize=()=>{const r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,1.5);w=r.width;h=r.height;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);pts=Array.from({length:Math.min(620,Math.floor(w*h/850))},(_,i)=>{const a=i*2.39996,radius=Math.sqrt(i/620),x=Math.cos(a)*radius,y=Math.sin(a)*radius,z=Math.sin(a*3+radius*5);return{x,y,z,s:.7+(z+1)*.55,ox:0,oy:0,vx:0,vy:0}})};
  const draw=()=>{ctx.clearRect(0,0,w,h);for(const p of pts){const depth=1+p.z*.14,bx=w*.54+p.x*w*.38*depth,by=h*.5+p.y*h*.43;const dx=bx+p.ox-mouse.current.x,dy=by+p.oy-mouse.current.y,dist=Math.hypot(dx,dy);if(mouse.current.active&&dist<105){const force=(1-dist/105)*1.7;p.vx+=(dx/(dist||1))*force;p.vy+=(dy/(dist||1))*force}p.vx+=-p.ox*.018;p.vy+=-p.oy*.018;p.vx*=.9;p.vy*=.9;p.ox+=p.vx;p.oy+=p.vy;const alpha=.22+(p.z+1)*.24;ctx.beginPath();ctx.arc(bx+p.ox,by+p.oy,p.s,0,7);ctx.fillStyle=p.x<0?`rgba(214,255,76,${alpha})`:`rgba(91,228,255,${alpha})`;ctx.fill()}if(!reduced)frame.current=requestAnimationFrame(draw)};
  resize();draw();const ro=new ResizeObserver(resize);ro.observe(c);return()=>{ro.disconnect();cancelAnimationFrame(frame.current)}
 },[]);
 return <canvas ref={canvas} className="point-cloud" aria-hidden="true" onPointerEnter={()=>{mouse.current.active=true}} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();mouse.current.x=e.clientX-r.left;mouse.current.y=e.clientY-r.top;mouse.current.active=true}} onPointerLeave={()=>{mouse.current.active=false}}/>;
}
function Logo(){return <a className="logo" href="#top"><i/>U2GS</a>}
function Nav(){const[open,setOpen]=useState(false);return <header><nav><Logo/><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">☰</button><div className={'navlinks '+(open?'open':'')}>{[['Overview','overview'],['Workflow','workflow'],['Capture Modes','modes'],['Showcase','showcase'],['Features','features'],['FAQ','faq']].map(([a,b])=><a key={b} href={'#'+b} onClick={()=>setOpen(false)}>{a}</a>)}<a className="nav-cta" href={FAB} target="_blank" rel="noreferrer">Get on Fab <Arrow/></a></div></nav></header>}
function Hero(){return <section id="overview" className="hero"><PointCloud/><div className="hero-copy"><p className="eyebrow">Unreal to Gaussian Splat 3.0</p><h1>Turn Unreal Engine scenes into <em>Gaussian Splat</em> datasets.</h1><p className="lede">Unreal to Gaussian Splat creates <strong>COLMAP-ready datasets</strong> <strong>directly inside Unreal Editor.</strong> Capture your scene, generate its point cloud, then train it in your 3DGS software of choice.</p><div className="hero-actions"><a className="button primary" href={FAB} target="_blank" rel="noreferrer">Get it on Fab <Arrow/></a><a className="button quiet" href="#showcase">Explore results <Arrow/></a></div></div><div className="hero-pipeline"><span>UNREAL SCENE</span><i>→</i><strong>COLMAP DATASET</strong><i>→</i><span>3DGS TRAINER</span><i>→</i><b>GAUSSIAN SPLAT</b></div><p className="hero-note">The plugin generates the dataset. Training happens afterward in compatible software.</p></section>}
function Workflow(){const steps=[['01','Capture Images','Render RGB views and write the COLMAP camera model.'],['02','Generate Point Cloud','Choose a density preset after image capture.'],['03','Color Point Cloud','Sample colors from the captured images.']];return <section id="workflow" className="section workflow"><div className="section-head"><p className="eyebrow">Inside Unreal Editor</p><h2>Three steps to a dataset that is ready to train.</h2></div><div className="flow"><div className="endpoint cyan">Unreal Engine<small>Your scene</small></div>{steps.map(s=><React.Fragment key={s[0]}><i className="connector">→</i><article className="flow-step"><b>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p></article></React.Fragment>)}<i className="connector">→</i><div className="endpoint lime">COLMAP-ready<small>Dataset</small></div></div><div className="boundary"><span>OUTSIDE THE PLUGIN</span><p>Postshot / LichtFeld Studio / compatible trainer <Arrow/> <strong>Gaussian Splat</strong></p></div></section>}
function Showcase(){const[active,setActive]=useState(0),[near,setNear]=useState(false),[ready,setReady]=useState(false),[slow,setSlow]=useState(false);const root=useRef(null),scene=scenes[active];useEffect(()=>{const ob=new IntersectionObserver(([e])=>{if(e.isIntersecting){setNear(true);ob.disconnect()}},{rootMargin:'300px'});ob.observe(root.current);return()=>ob.disconnect()},[]);useEffect(()=>{setReady(false);setSlow(false);if(!near)return;const t=setTimeout(()=>setSlow(true),25000);return()=>clearTimeout(t)},[active,near]);const choose=i=>{setActive((i+scenes.length)%scenes.length);setNear(true)};return <section id="showcase" className="section showcase" ref={root}><div className="showcase-top"><div><p className="eyebrow">Live 3D gallery</p><h2>Created in Unreal.<br/>Explorable as Gaussian Splats.</h2></div><p>Ten real scenes. One live viewer at a time for fast, reliable loading.</p></div><div className="gallery-shell"><div className="gallery-view">{!ready&&<div className="load-state"><span/><b>{scene[1]}</b><small>Loading interactive splat…</small></div>}{near&&<iframe key={scene[0]} title={`${scene[1]} interactive Gaussian Splat`} src={`https://superspl.at/s?id=${scene[0]}`} allow="fullscreen; xr-spatial-tracking" loading="lazy" onLoad={()=>setReady(true)}/>} {slow&&<a className="slow-link" href={`https://superspl.at/scene/${scene[0]}`} target="_blank" rel="noreferrer">Open directly in SuperSplat ↗</a>}</div><aside className="gallery-info"><p className="counter">{String(active+1).padStart(2,'0')} / 10</p><h3>{scene[1]}</h3><p>Created by {scene[2]}</p><div className="gallery-arrows"><button onClick={()=>choose(active-1)} aria-label="Previous scene">←</button><button onClick={()=>choose(active+1)} aria-label="Next scene">→</button></div><a href={`https://superspl.at/scene/${scene[0]}`} target="_blank" rel="noreferrer">View full scene ↗</a></aside></div><div className="scene-rail">{scenes.map((s,i)=><button key={s[0]} onClick={()=>choose(i)} className={i===active?'active':''}><span>{String(i+1).padStart(2,'0')}</span><b>{s[1]}</b><small>{s[2]}</small></button>)}</div></section>}
function ModeVisual({type,src,title}){return <div className={'mode-visual '+type}><img src={src} alt="" loading="lazy"/><span/></div>}
function Modes(){return <section id="modes" className="section modes"><div className="section-head"><p className="eyebrow">Capture modes</p><h2>Build a capture plan that matches the scene.</h2><p>Purpose-built camera placement for objects, paths, spaces and large exterior maps.</p></div><div className="mode-grid">{modes.map(([type,title,copy,src])=><article key={type}><ModeVisual type={type} src={src} title={title}/><div className="mode-copy"><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>}
function Features(){return <section id="features" className="section features"><div className="feature-intro"><p className="eyebrow feature-label">What's New in 3.0</p><h2>Capture faster.<br/>Iterate with control.</h2></div><article className="speed-card"><span>UP TO APPROXIMATELY</span><strong>4×</strong><h3>faster image capture in tested projects</h3><p>Performance varies by scene, settings, storage and hardware.</p></article><div className="feature-cards"><article><b>Movie Render Queue</b><p>Anti-aliasing, temporal and spatial sampling controls.</p></article><article><b>Oblique Capture Rig</b><p>Smart Ortho 3-View and Smart Oblique 5-View.</p></article><article><b>Independent stages</b><p>Generate, color and export without repeating capture.</p></article><article><b>Density after capture</b><p>Change point-cloud density from existing RGB images.</p></article></div><aside className="iteration"><p className="eyebrow">Iteration without a full reset</p><h3>Adjust the point-cloud stage without necessarily recapturing everything.</h3><div className="iteration-grid">{iteration.map(x=><span key={x}>{x}</span>)}</div></aside></section>}
function Compatibility(){const audiences=['Arch-viz','Product Visualization','Game Development','Technical Art','Research','3DGS / NeRF'];return <section className="section compat"><div className="audience"><p className="eyebrow">Built for technical workflows</p><h2>Built for technical 3D workflows.</h2><div className="audience-tags">{audiences.map(x=><span key={x}>{x}</span>)}</div></div><div className="requirements"><article><small>Platform</small><b>Windows</b></article><article><small>Unreal Engine</small><b>5.4 — 5.8</b></article><article><small>Required plugins</small><b>Python Editor Script Plugin</b><b>Editor Scripting Utilities</b><b>Movie Render Queue</b></article></div></section>}
function FAQ(){const[open,setOpen]=useState(0);return <section id="faq" className="section faq"><div className="section-head"><p className="eyebrow">FAQ</p><h2>Technical answers, plainly stated.</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><article key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}>{q}<span>{open===i?'−':'+'}</span></button><div className={'answer '+(open===i?'open':'')}><p>{a}</p></div></article>)}</div></section>}
function App(){return <><Nav/><main id="top"><Hero/><Workflow/><Showcase/><Modes/><Features/><Compatibility/><FAQ/><section className="section final"><p className="eyebrow">Start from the scene you already have</p><h2>Ready to turn your Unreal scene into a Gaussian Splat dataset?</h2><div className="hero-actions"><a className="button primary" href={FAB} target="_blank" rel="noreferrer">Get it on Fab <Arrow/></a><a className="button quiet" href={DOCS} target="_blank" rel="noreferrer">Read documentation</a><a className="button quiet" href={DISCORD} target="_blank" rel="noreferrer">Join Discord</a></div></section></main><footer><Logo/><p>Unreal to Gaussian Splat — Automated COLMAP Dataset Generator</p><a href={FAB}>Fab ↗</a><a href={DOCS}>Docs ↗</a><a href={DISCORD}>Discord ↗</a></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
